### ISSUE TITLE
Hugo theme collection?

### ISSUE THREAD

**Issue by harshakokel** [bep/editorial#1]
Hello,

I was looking for editorial theme in Hugo but did not find one. Is this theme usable? If so, I suggest you add this theme to Hugo themes [here](https://gohugo.io/contribute/themes/#add-your-theme-to-the-repo). It might help people like me who want to use editorial theme in Hugo.

**Comment by bep** [comment]
I have a little too many things going on and, honestly, I don't remember the status of this theme. But I do agree that Hugo needs a solid editorial theme.
